collapse_single_pages: true
nav:
  - index.md
  - quick_start
  - basic_operations.md
  - FAQ.md
  - memory_tuning.md
  - mindstudio_insight_install_guide.md
  - operator_tuning.md
  - overview.md
  - service_optimization.md
  - system_tuning.md
