collapse_single_pages: true
nav:
  - index.md
  - basic_operations
  - FAQ
  - install_guide
  - memory_tuning
  - operator_tuning
  - quick_start
  - readme
  - service_optimization
  - system_tuning
